/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "arn": string
      "invokeArn": string
      "name": string
      "roleArn": string
      "type": "sst.aws.Function"
      "url": string
    }
    "AppData": {
      "isDevMode": boolean
      "isProdStage": boolean
      "name": string
      "stage": string
      "type": "sst.sst.Linkable"
    }
    "AppsyncEventApi": {
      "dns": {
        "http": string
        "realtime": string
      }
      "type": "pulumi-nodejs.dynamic.Resource"
    }
    "AuthTable": {
      "arn": string
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Aws": {
      "account": {
        "id": string
      }
      "region": string
      "type": "sst.sst.Linkable"
    }
    "BudgetEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Cloudflare": {
      "account": {
        "id": string
      }
      "type": "sst.sst.Linkable"
    }
    "CloudflareAccountId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudflareApiToken": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "CloudfrontApiCachePolicy": {
      "id": string
      "type": "aws.cloudfront/cachePolicy.CachePolicy"
    }
    "CloudfrontKeyGroup": {
      "id": string
      "type": "aws.cloudfront/keyGroup.KeyGroup"
    }
    "CloudfrontPrivateKey": {
      "pem": string
      "type": "tls.index/privateKey.PrivateKey"
    }
    "CloudfrontPublicKey": {
      "id": string
      "type": "aws.cloudfront/publicKey.PublicKey"
    }
    "CloudfrontRewriteUriFunction": {
      "arn": string
      "type": "aws.cloudfront/function.Function"
    }
    "CloudfrontS3OriginAccessControl": {
      "id": string
      "type": "aws.cloudfront/originAccessControl.OriginAccessControl"
    }
    "CodeBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ConfigTable": {
      "arn": string
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DbMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Domains": {
      "api": string
      "auth": string
      "realtime": string
      "root": string
      "type": "sst.sst.Linkable"
      "web": string
      "www": string
    }
    "DsqlCluster": {
      "database": string
      "host": string
      "port": number
      "ssl": boolean
      "type": "pulumi-nodejs.dynamic.Resource"
      "user": string
    }
    "IdentityProviders": {
      "entra_id": {
        "clientId": string
        "clientSecret": string
      }
      "google": {
        "clientId": string
        "clientSecret": string
      }
      "type": "sst.sst.Linkable"
    }
    "InfraDeadLetterQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "InfraQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "InvoicesProcessor": {
      "arn": string
      "invokeArn": string
      "name": string
      "roleArn": string
      "type": "sst.aws.Function"
    }
    "Issuer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "PapercutSync": {
      "arn": string
      "invokeArn": string
      "name": string
      "roleArn": string
      "type": "sst.aws.Function"
    }
    "PulumiBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PulumiRole": {
      "arn": string
      "name": string
      "type": "aws.iam/role.Role"
    }
    "PulumiRoleExternalId": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "RealtimePublisherRole": {
      "arn": string
      "name": string
      "type": "aws.iam/role.Role"
    }
    "RealtimePublisherRoleExternalId": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "RealtimeSubscriberRole": {
      "arn": string
      "name": string
      "type": "aws.iam/role.Role"
    }
    "RealtimeSubscriberRoleExternalId": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "ReplicacheLicenseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ReverseProxyWorker": {
      "type": "sst.cloudflare.Worker"
    }
    "RootDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "RouterSecret": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "TemporaryBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "TenantDomains": {
      "cdn": {
        "nameTemplate": string
      },
      "api": {
        "nameTemplate": string
      },
      "realtime": {
        "nameTemplate": string
      },
      "type": "sst.sst.Linkable"
    },
    "TenantRoles": {
      "apiAccess": {
        "nameTemplate": string
      }
      "bucketsAccess": {
        "nameTemplate": string
      }
      "realtimePublisher": {
        "nameTemplate": string
      }
      "realtimeSubscriber": {
        "nameTemplate": string
      }
      "type": "sst.sst.Linkable"
      "updateConfig": {
        "nameTemplate": string
      }
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "WebPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Www": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}