/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ApexDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "arn": string
      "name": string
      "roleArn": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiClientCredentialsConfigurationProfileTemplate": {
      "name": string
      "type": "pd.templates.AwsAppConfigConfigurationProfile"
    }
    "ApiGateway": {
      "type": "pd.cloudflare.Worker"
      "urls": {
        "api": string
        "auth": string
      }
    }
    "ApiGatewayAwsPermissions": {
      "type": "sst.sst.Linkable"
    }
    "AppconfigAgent": {
      "port": number
      "type": "sst.sst.Linkable"
    }
    "AppconfigAgentDevRole": {
      "arn": string
      "externalId": string
      "name": string
      "type": "pd.aws.IamExternalRole"
    }
    "AppconfigAllAtOnceDeploymentStrategy": {
      "arn": string
      "id": string
      "type": "aws.appconfig/deploymentStrategy.DeploymentStrategy"
    }
    "AppconfigApplication": {
      "arn": string
      "id": string
      "name": string
      "type": "aws.appconfig/application.Application"
    }
    "AppconfigEnvironment": {
      "arn": string
      "id": string
      "name": string
      "type": "aws.appconfig/environment.Environment"
    }
    "AppconfigLinear20PercentEvery6MinutesDeploymentStrategy": {
      "arn": string
      "id": string
      "type": "aws.appconfig/deploymentStrategy.DeploymentStrategy"
    }
    "AppconfigRoleTemplate": {
      "arn": string
      "name": string
      "type": "pd.templates.AwsIamRole"
    }
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AssetsBucketAccessPointTemplate": {
      "name": string
      "type": "pd.templates.AwsS3AccessPoint"
    }
    "AssetsKeyGroup": {
      "id": string
      "type": "aws.cloudfront/keyGroup.KeyGroup"
    }
    "AssetsPrivateKey": {
      "pem": string
      "type": "tls.index/privateKey.PrivateKey"
    }
    "AssetsRouter": {
      "distributionId": string
      "keyValueStoreArn": string
      "keyValueStoreNamespace": string
      "type": "sst.aws.Router"
      "url": string
    }
    "Aws": {
      "account": {
        "id": string
      }
      "region": string
      "type": "sst.sst.Linkable"
    }
    "Cloudflare": {
      "account": {
        "id": string
      }
      "apiToken": string
      "type": "sst.sst.Linkable"
    }
    "DevBridgeCodeUseast2Bridge": {
      "bucket": string
      "key": string
      "type": "aws.s3/bucketObjectv2.BucketObjectv2"
    }
    "Dsql": {
      "database": string
      "host": string
      "port": number
      "ssl": boolean
      "type": "sst.aws.Dsql"
      "user": string
    }
    "Dynamo": {
      "globalSecondaryIndexes": {
        "gsi1": {
          "hashKey": string
          "rangeKey": string
        }
      }
      "hashKey": string
      "keyLiterals": {
        "CLIENT": string
        "DEPLOYMENT": string
        "INFRA": string
        "INPUT": string
        "IP": string
        "ORDER": string
        "OUTPUT": string
        "ROOM": string
        "TENANT": string
        "USER": string
      }
      "name": string
      "rangeKey": string
      "type": "sst.aws.Dynamo"
    }
    "Environment": {
      "isDevMode": boolean
      "isProdStage": boolean
      "type": "sst.sst.Linkable"
    }
    "Hostnames": {
      "api": string
      "assets": string
      "auth": string
      "papercutApiTemplate": string
      "realtime": string
      "type": "sst.sst.Linkable"
      "web": string
      "www": string
    }
    "IdentityProviders": {
      "entra_id": {
        "clientId": string
        "clientSecret": string
      }
      "google": {
        "clientId": string
        "clientSecret": string
      }
      "type": "sst.sst.Linkable"
    }
    "InfraManagerFailureTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "InvoicesProcessor": {
      "arn": string
      "name": string
      "roleArn": string
      "type": "sst.aws.Function"
    }
    "InvoicesProcessorClientCredentialsConfigurationProfileTemplate": {
      "name": string
      "type": "pd.templates.AwsAppConfigConfigurationProfile"
    }
    "InvoicesProcessorQueueSenderRoleTemplate": {
      "arn": string
      "name": string
      "type": "pd.templates.AwsIamRole"
    }
    "Issuer": {
      "arn": string
      "name": string
      "roleArn": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Migrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "NanoId": {
      "alphabet": string
      "length": number
      "pattern": string
      "type": "sst.sst.Linkable"
    }
    "PapercutApiAuthTokenConfigurationProfileTemplate": {
      "name": string
      "type": "pd.templates.AwsAppConfigConfigurationProfile"
    }
    "PapercutApiGatewayAwsAccessKey": {
      "id": string
      "secret": string
      "type": "pd.aws.IamAccessKey"
    }
    "PapercutApiGatewayScriptObject": {
      "bucket": string
      "key": string
      "type": "aws.s3/bucketObjectv2.BucketObjectv2"
    }
    "PapercutSync": {
      "arn": string
      "name": string
      "roleArn": string
      "type": "sst.aws.Function"
    }
    "PapercutSyncClientCredentialsConfigurationProfileTemplate": {
      "name": string
      "type": "pd.templates.AwsAppConfigConfigurationProfile"
    }
    "PulumiBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PulumiRole": {
      "arn": string
      "externalId": string
      "name": string
      "type": "pd.aws.IamExternalRole"
    }
    "RateLimit": import("@cloudflare/workers-types").RateLimit
    "RealtimeApi": {
      "arn": string
      "dns": {
        "http": string
        "realtime": string
      }
      "id": string
      "type": "aws.appsync/api.Api"
    }
    "RealtimeChannelNamespacePublisherRoleTemplate": {
      "arn": string
      "name": string
      "type": "pd.templates.AwsIamRole"
    }
    "RealtimeChannelNamespaceSubscriberRoleTemplate": {
      "arn": string
      "name": string
      "type": "pd.templates.AwsIamRole"
    }
    "SnsTopicEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "pd.cloudflare.StaticSite"
      "url": string
    }
    "Www": {
      "type": "sst.cloudflare.TanStackStart"
      "url": string
    }
    "Zone": {
      "id": string
      "name": string
      "type": "sst.sst.Linkable"
    }
  }
}

import "sst"
export {}