import { recommended } from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    sortImports: {
      newlinesBetween: false,
      groups: [
        "value-builtin",
        { newlinesBetween: true },
        "value-external",
        { newlinesBetween: true },
        ["value-parent", "value-sibling", "value-index"],
        { newlinesBetween: true },
        "type-builtin",
        "type-external",
        "type-parent",
        "type-sibling",
        "type-index",
      ],
    },
    ignorePatterns: [
      "node_modules",
      "routeTree.gen.ts",
      "dist",
      ".sst",
      "migrations",
      "sst-env.d.ts",
    ],
  },
  lint: {
    extends: [recommended],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    plugins: ["eslint", "unicorn", "typescript", "react", "react-perf"],
    jsPlugins: [
      "@stylexjs/eslint-plugin",
      "@tanstack/eslint-plugin-router",
      "eslint-plugin-drizzle",
    ],
    categories: {
      correctness: "error",
      suspicious: "error",
      pedantic: "off",
      perf: "warn",
      style: "off",
      restriction: "error",
    },
    rules: {
      "@stylexjs/valid-styles": "error",
      "@stylexjs/sort-keys": "warn",
      "effecttsgo/async-function": "off",
      "eslint/no-new": "off",
      "eslint/no-param-reassign": "off",
      "eslint/no-shadow": "off",
      "eslint/no-undefined": "off",
      "eslint/no-underscore-dangle": "off",
      "eslint/no-use-before-define": "off",
      "react/forbid-component-props": "off",
      "react/jsx-filename-extension": "off",
      "react/no-unknown-property": "off",
      "react-perf/jsx-no-new-array-as-prop": "off",
      "react-perf/jsx-no-new-function-as-prop": "off",
      "react/react-in-jsx-scope": "off",
      "typescript/consistent-return": "off",
      "typescript/explicit-function-return-type": "off",
      "typescript/explicit-module-boundary-types": "off",
      "typescript/no-namespace": "off",
      "typescript/promise-function-async": "off",
      "typescript/no-invalid-void-type": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/no-array-reduce": "off",
    },
    ignorePatterns: ["**/sst-env.d.ts", "**/routeTree.gen.ts"],
    overrides: [
      {
        files: ["sst.config.ts", "./infra/**", "packages/typescript/vendor/openauth/**"],
        rules: {
          "effecttsgo/crypto-random-uuid": "off",
          "effecttsgo/extends-native-error": "off",
          "effecttsgo/global-console": "off",
          "effecttsgo/global-date": "off",
          "effecttsgo/global-fetch": "off",
          "effecttsgo/process-env": "off",
          "effecttsgo/node-builtin-import": "off",
        },
      },
    ],
  },
});
