/* This file auto-generated by SST. Do not edit */
/* oxlint-disable */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_RESOURCE_ReverseProxy: string
  readonly VITE_RESOURCE_Environment: string
  readonly VITE_RESOURCE_Hostnames: string
  readonly VITE_RESOURCE_App: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}