#:schema node_modules/wrangler/config-schema.json
name = "printworks-api-rate-limiters"
main = "src/index.ts"
compatibility_date = "2024-09-03"

[[unsafe.bindings]]
name = "USER_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[[unsafe.bindings]]
name = "IP_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 5000, period = 60 }
