/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_RESOURCE_AppData: string
  readonly VITE_RESOURCE_Auth: string
  readonly VITE_RESOURCE_ReplicacheLicenseKey: string
  readonly VITE_RESOURCE_Router: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}