[project]
name = "infra"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "aws-lambda-powertools[parser,tracer]>=3.12.0",
    "boto3>=1.38.13",
    "pulumi>=3.169.0",
    "pulumi-aws>=6.80.0",
    "pulumi-cloudflare>=5.49.1",
    "requests>=2.32.3",
    "sst",
    "types-boto3-appsync>=1.38.2",
    "types-boto3-ssm>=1.38.5",
    "types-boto3-sts>=1.38.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]

[tool.uv.sources]
sst = { git = "https://github.com/sst/sst", subdirectory = "sdk/python", branch = "dev" }
