class Resource:
    class AppData:
        isDevMode: bool
        isProdStage: bool
        name: str
        stage: str
        type: str
    class Api:
        arn: str
        invokeArn: str
        name: str
        roleArn: str
        type: str
        url: str
    class Aws:
        class account:
            id: str
        region: str
        type: str
    class CloudflareApiToken:
        type: str
        value: str
    class CloudfrontApiCachePolicy:
        id: str
        type: str
    class CloudfrontKeyGroup:
        id: str
        type: str
    class CloudfrontPublicKey:
        id: str
        type: str
    class CloudfrontRewriteUriFunction:
        arn: str
        type: str
    class CloudfrontS3OriginAccessControl:
        id: str
        type: str
    class ConfigTable:
        name: str
        type: str
    class Domains:
        api: str
        auth: str
        root: str
        type: str
        web: str
        www: str
    class InvoicesProcessor:
        arn: str
        invokeArn: str
        name: str
        roleArn: str
        type: str
    class PapercutSync:
        arn: str
        invokeArn: str
        name: str
        roleArn: str
        type: str
    class PapercutTailgateImage:
        uri: str
        type: str
    class PapercutTailgateResourceCiphertext:
        encryptionKey: str
        type: str
    class PulumiBucket:
        name: str
        type: str
    class PulumiRole:
        arn: str
        name: str
        type: str
    class PulumiRoleExternalId:
        type: str
        value: str
    class RealtimePublisherRole:
        arn: str
        name: str
        type: str
    class RealtimePublisherRoleExternalId:
        type: str
        value: str
    class TenantBuckets:
        class assets:
            nameTemplate: str
        class documents:
            nameTemplate: str
        type: str
    class TenantDomains:
        class api:
            nameTemplate: str
        class files:
            nameTemplate: str
        class realtime:
            nameTemplate: str
        type: str
    class TenantRoles:
        class apiAccess:
            nameTemplate: str
        class bucketsAccess:
            nameTemplate: str
        class realtimePublisher:
            nameTemplate: str
        class realtimeSubscriber:
            nameTemplate: str
        type: str
    class Vpc:
        id: str
        cloudmapNamespaceId: str
        type: str
    class VpcLink:
        id: str
        type: str
    class Zone:
        id: str
        name: str
        type: str
