import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";

import { Constants } from "@printdesk/core/utils/constants";
import * as R from "remeda";

import { PhysicalName } from "../physical-name";

import { siteBuilder } from "~/sst/aws/helpers/site-builder";
import { URL_UNAVAILABLE } from "~/sst/aws/linkable";
import { buildApp } from "~/sst/base/base-static-site";
import { transform } from "~/sst/component";
import { VisibleError } from "~/sst/error";
import { Link } from "~/sst/link";

export interface StaticSiteArgs extends sst.cloudflare.StaticSiteV2Args {
  server: $util.Input<{
    handler: $util.Input<string>;
    routes: $util.Input<Array<string>>;
    // oxlint-disable-next-line typescript/no-explicit-any
    link?: $util.Input<any>;
  }>;
}

export class StaticSite extends $util.ComponentResource implements Link.Linkable {
  public static readonly __pulumiType = "pd:cloudflare:StaticSite";

  readonly #server?: sst.cloudflare.Worker;
  #devUrl = $output(URL_UNAVAILABLE);

  public constructor(name: string, args: StaticSiteArgs, opts?: $util.ComponentResourceOptions) {
    super(StaticSite.__pulumiType, name, {}, opts);

    const path = $output(args.path).apply((path) => {
      if (!path) return ".";
      if (!existsSync(path)) throw new VisibleError(`No site found at "${resolve(path)}".`);
      return path;
    });

    const environment = $util
      .all([
        $output(args.environment),
        $jsonStringify({ name: $app.name, stage: $app.stage }),
      ] as const)
      .apply(
        ([env, app]) =>
          ({ ...env, [`${Constants.VITE_RESOURCE_PREFIX}App`]: app }) as Record<string, string>,
      );

    const serverName = new PhysicalName(
      `${name}Server`,
      { max: 64, transform: (name) => name.toLowerCase() },
      { parent: this },
    );

    const compatibilityDate = new Date().toISOString().slice(0, 10);
    const compatibilityFlags = ["nodejs_compat"];
    const htmlHandling = normalizeHtmlHandling();
    const notFoundHandling = normalizeNotFoundHandling();
    const runWorkerFirst = $output(args.server).apply(R.prop("routes"));

    $resolve({
      path,
      config: $jsonStringify(
        {
          $schema: "node_modules/wrangler/config-schema.json",
          name: serverName.result,
          compatibility_date: compatibilityDate,
          compatibility_flags: compatibilityFlags,
          main: $output(args.server).apply(R.prop("handler")),
          vars: environment,
          assets: {
            binding: "ASSETS",
            html_handling: htmlHandling,
            not_found_handling: notFoundHandling,
            run_worker_first: runWorkerFirst,
          },
        },
        undefined,
        2,
      ),
      environment,
    }).apply(({ path, config, environment }) => {
      const configPath = resolve(join(path, "wrangler.jsonc"));
      mkdirSync(dirname(configPath), { recursive: true });
      writeFileSync(configPath, config);

      siteBuilder(
        `${name}ServerTypegen`,
        {
          create: "vpx wrangler types",
          dir: join($cli.paths.root, path),
          triggers: [config],
        },
        { parent: this },
      );

      const typesPath = resolve(join(path, "src/sst-env.d.ts"));
      mkdirSync(dirname(typesPath), { recursive: true });
      writeFileSync(
        typesPath,
        `/* This file auto-generated by SST. Do not edit */
/* oxlint-disable */

/// <reference types="vite/client" />
interface ImportMetaEnv {
${Object.keys(environment)
  .map((key) => `  readonly ${key}: string`)
  .join("\n")}
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}`,
      );
    });

    const dev = normalizeDev();

    if (dev.enabled) {
      this.#devUrl = dev.url;
      this.registerOutputs({
        _hint: undefined,
        _dev: dev.outputs,
        _metadata: {
          mode: "placeholder",
          path,
          environment,
          url: this.url,
        },
      });
      return;
    }

    const directory = buildApp(this, name, args.build, path, environment);

    this.#server = new sst.cloudflare.Worker(
      ...transform(
        args.transform?.server,
        `${name}Server`,
        {
          handler: $resolve({ path, handler: $output(args.server).apply(R.prop("handler")) }).apply(
            ({ path, handler }) => join(path, handler),
          ),
          environment,
          dev: false,
          domain: args.domain,
          assets: {
            directory,
            htmlHandling,
            notFoundHandling,
            runWorkerFirst,
          },
        },
        { parent: this },
      ),
    );

    this.registerOutputs({
      _hint: this.url,
      _dev: dev.outputs,
      _metadata: {
        mode: "deployed",
        path,
        environment,
        url: this.url,
      },
    });

    function normalizeDev() {
      const enabled = $dev && args.dev !== false;
      const devArgs = args.dev || {};

      return {
        enabled,
        url: $output(devArgs.url ?? URL_UNAVAILABLE),
        outputs: {
          title: devArgs.title,
          environment,
          command: $output(devArgs.command ?? "vp run dev"),
          autostart: $output(devArgs.autostart ?? true),
          directory: $output(devArgs.directory ?? path),
        },
      };
    }

    function normalizeHtmlHandling() {
      return args.trailingSlash === "force"
        ? "force-trailing-slash"
        : args.trailingSlash === "drop"
          ? "drop-trailing-slash"
          : "auto-trailing-slash";
    }

    function normalizeNotFoundHandling() {
      return args.notFound === "404" ? "404-page" : "single-page-application";
    }
  }

  public get url() {
    return this.#server?.url ?? this.#devUrl;
  }

  public get nodes() {
    return {
      server: this.#server,
    };
  }

  public getSSTLink() {
    return {
      properties: { url: this.url },
    };
  }
}
